### PR TITLE
Update VIPB file with new repo location, LICENSE

### PR DESCRIPTION
**Pull request by rtzoeller**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-custom-device-inline-async-api/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Update the VI package spec with the new repo location and license information

### Why should this Pull Request be merged?

The current VIPC file is outdated.

### What testing has been done?

Built a VIPC file and confirmed that it installed the tools successfully in 2015.

### CODE REVIEW

**Comment by rtzoeller** [comment]
When this is merged, I will create a release on GitHub of the VI package.

**Comment by csjall** [comment]
- [x] I am unable to open/build the vi package. 
image
- [x] Add built folder to gitignore. Since we are adding vi package as a release asset, we don't want to check it into source code.
- [x] Update README with some basic build instructions.

**Comment by rtzoeller** [comment]
The VI package file opens fine on my machine. I'll try on some other machines to track down whether the issue lies.

**Comment by rtzoeller** [comment]
@csjall I've recreated this in an older version of VIPM. I think that they bumped the save file format between the f0 and f1 builds we had, and it was causing things not to work despite the rest of the file being identical.

Do we want to bump the version to 1.0.1 (or similar) for the first provided build? All previous releases have been 1.0.0, so differentiating from that might be helpful.

**Comment by csjall** [comment]
> @csjall I've recreated this in an older version of VIPM. I think that they bumped the save file format between the f0 and f1 builds we had, and it was causing things not to work despite the rest of the file being identical.
> 
> Do we want to bump the version to 1.0.1 (or similar) for the first provided build? All previous releases have been 1.0.0, so differentiating from that might be helpful.

We should keep the version the same until something actually changes which is incompatible.

**Review by buckd — APPROVED** [review]

**Pull request merged**
